server:
  port: 9003

database:
  name: ${DATABASE:doctor_db}
  username: ${DB_USERNAME:postgres}
  password: ${DB_PASSWORD:postgres} 
  port: ${DB_PORT:5432}
  host: ${DB_HOST:localhost}
  type: ${DB_TYPE:postgresql}
  
spring:
  application:
    name: auth
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQL82Dialect
      database: POSTGRESQL
      show-sql: false
      hibernate:
         ddl-auto: none 
  datasource:
        type: org.apache.commons.dbcp2.BasicDataSource
        url: jdbc:${database.type}://${database.host}:${database.port}/${database.name}
        name:
        username: ${database.username}
        password: ${database.password}
        dbcp2:
           max-idle: 2
           min-idle: 0
           max-conn-lifetime-millis: 0
           initial-size: 5
           max-total: 10
           test-while-idle: false
           test-on-borrow: false
           log-abandoned: true
           remove-abandoned-on-borrow: true
           remove-abandoned-on-maintenance : true
           remove-abandoned-timeout: 10
           abandoned-usage-tracking: true
           additionalProperties:

  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:config/liquibase/master.xml

  mail:
    host: ${MAIL_HOST:smtp.zoho.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:welcome@iflhousingfinance.com}
    password: ${MAIL_PASSWORD:Welcome@2021}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 60000
          timeout: 60000
          writetimeout: 60000
          
# INFO ENDPOINT CONFIGURATION
info:
 app:
  name: auth
  version: 0.0.1-SNAPSHOT
  description: The auth server project
  java:
   version: 1.8

management:
 endpoint:
  health:
   show-details: always
 health:
  mail:
    enabled: false

## swagger ##
springdoc:
  api-docs:
    path: /actuator/api-docs            

eureka:
  instance:
    preferIpAddress: true
    ip-address: ${ECS_INSTANCE_IP_ADDRESS:127.0.0.1}
    nonSecurePort: ${server.port}
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    homePageUrl: /
  client:
    enabled: true
    healthcheck:
     enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${SERVICE_DISCOVERY_BASE_URL:http://localhost:9001}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

logging:
  level:
    root: ERROR
    com.arg: DEBUG
  file:  /tmp/logs/${spring.application.name}/${spring.application.name}-log.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 
      
auth:
  clientid: talk2amareswaran
  clientSecret: talk2amareswaran@123
  privateKey: -----BEGIN RSA PRIVATE KEY-----MIIEpAIBAAKCAQEAsY9wY6rwdql0GCPFxu7eEypLC8TkDQHgaFlmP5QBf7Il4/8/ogTrT1cLF/fMrfhoJrPeZWjzP6NmaxttCUcki8JSbmaxdYNnIPHsPFvqr1DlpvikdKiG5lkKS27E9uUQ1XmeXh9Vhn9QwLQyXl5bbbjlDewiCzB/MuKlbuuxFsb7ZPpBD+rE69efUfTu8dZPa5QzTugqxqAe9q2soLPxYyh91BGjVGWMN9wwWnM+WaQ9IehuQko7drlvJRVhPow9zvzTanaJckn02+Ubj5+LFQ8yYNe/PQQSS+noaQtmCqRfVhL161F6yivj16EuYJhkUn3TQQTbDhSU3CcdMcX5lQIDAQABAoIBABXGVm0SmHyk2UTgli+IOZm2FQ/zbFggA8ooNH7Vgr2LNlRYiBAxdD39mbGtxN8M2JDue/aJwVLrkfLOoTeDDvtIsF0zoM2deLc0k9jvGL+5NwCb+2cHB8wV3UpU4ji47LCRQpeeVhmxYVDQiGDER4gUJZroe2BN6TtvSgRpSQVW2z6Fd26e3ywHchDZBm/Uj5piXbbUaNVngy/SehiGD9ETCkeFkHyjCETOS1ot4hpN6j7ovyZQdDJVc4ERmmd9V28d4m1Av9yoLSiNYnECpkhH4KuteHQ/keO3bq8mOgeKNtReTadHPVAjkq4sF4ZlsTUru7JNGmFv1yLsUWh4Ex0CgYEA4J972qFv+i//wjg3Q2YdvmCx7zT3SA4Fs+1vlcbW35iEQ96SQS5ToPl47+yev2j+rXswsyjKdW1t9PbgfmKSmxtbnbNyzX6u2RlbxwazMGIwGg8Z7ITWr9Y65PtKea3fsNBKiwR3jT97KB5wl/wJK5GvFYFt1M3cSKv5qQbsgu8CgYEAylz+i4Fbzk3uii290f8fkHiNudKWRoWAHu3sdBV0dFbkt4Ec5QZkUyb9aeLZbI4YDdNHo6+aAQCcOp4qU+7vgkLUSMIoTCK/I8N5iA9Ws3lvnLaVJJ8j64M+HV7A+zaRtKbPVDRBt4oWuzjMhBgCs0NPVa9BgpYmwqfltgN++7sCgYBWBl49pfQnofhWXoczpckgXxHmJafKjaw7c2R3vRYPve5xu6zRj7dxf/mEEV/euIxIzlQhWS7oeAdTeLUTUhcJlhmpNM9zyd+Wv3J5r6QylHgNktj/zwQVhXs6tM6Z+TAhHDRgN0695qD5BWdjnZ+5curV1qLEjC6gGlTcGg28OwKBgQDGr4uUuUvEQSwGK2cGOfFpzZOJcUPutcDXnU7dovsWBwLFUVVnYGE8aznAruQ++zyOxnS+N/mDJnA99XElu6EZSjhXv5oFNtBoctJuTnEYAhEd0v6YWE/SOqfP+mqLvEZPEsDZsf0cEc7Dv769qz1reJj6TfqKFpaz5Flb3g7dZQKBgQCfD4iTDLsCtdmZ7qENAQ26UYES/C+/cYbuPBnme3B7C14YeDXE1bVFk0GPxIwCisyiM0aayuM4o7kQFsF0ChV7XP5leTdGusZWACDnyP1vibAAnPde7fAqHiX4PZOYaKVBS0cCjZQfZHV/ilcD0EvYt6e61n+qozJfYDOVyimqIQ==-----END RSA PRIVATE KEY-----
  publicKey: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsY9wY6rwdql0GCPFxu7eEypLC8TkDQHgaFlmP5QBf7Il4/8/ogTrT1cLF/fMrfhoJrPeZWjzP6NmaxttCUcki8JSbmaxdYNnIPHsPFvqr1DlpvikdKiG5lkKS27E9uUQ1XmeXh9Vhn9QwLQyXl5bbbjlDewiCzB/MuKlbuuxFsb7ZPpBD+rE69efUfTu8dZPa5QzTugqxqAe9q2soLPxYyh91BGjVGWMN9wwWnM+WaQ9IehuQko7drlvJRVhPow9zvzTanaJckn02+Ubj5+LFQ8yYNe/PQQSS+noaQtmCqRfVhL161F6yivj16EuYJhkUn3TQQTbDhSU3CcdMcX5lQIDAQAB-----END PUBLIC KEY-----
  check-user-scopes: true
  resourceId: ms/arg
  mfa:
    codeLength: 4
    expTimeInSec: 300
    subject: "One Time password"
    loginOtp: "Dear %s, Your OTP is %s. You should not share this OTP with anyone else. Team IFL"
    forgetPwdText: "Dear %s, Your OTP is %s. You should not share this OTP with anyone else. Team IFL"
    
  smsapi:
     baseUrl: http://125.16.147.178
     ukey: 222
     language: 0
     credittype: 2
     senderid: IFLHFL
     templateid: 0
     filetype: 2
     
     
     
     