server:
    port: 9002

spring:
  application:
    name: gateway

eureka:
  instance:
    preferIpAddress: true
    ip-address: ${ECS_INSTANCE_IP_ADDRESS:127.0.0.1}
    nonSecurePort: ${server.port}
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    homePageUrl: /
  client:
    enabled: true
    healthcheck:
     enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${SERVICE_DISCOVERY_BASE_URL:http://localhost:9001}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
    
logging:
  level:
    root: ERROR
    com.arg: DEBUG
  file:  /tmp/logs/${spring.application.name}/${spring.application.name}-log.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
     
