server:
  port: 9004
  
service:
  endpoints:
    excluded: /public/**,/webjars/**,/actuator/**,/v1/oauth/**
  administrator:
    username: user-administrator
    password: password       

database:
  name: ${DATABASE:doctor_db}
  username: ${DB_USERNAME:postgres}
  password: ${DB_PASSWORD:postgres} 
  port: ${DB_PORT:5432}
  host: ${DB_HOST:localhost}
  type: ${DB_TYPE:postgresql}
  
spring:
  application:
    name: cms
  security:
   oauth2:
     resourceserver:
       #jwt:
       #  public-key-location: classpath:publicKey.pub
        opaque-token:
          introspection-uri: ${GATEWAY_BASE_URL:http://localhost:9002}/auth/oauth/check_token
          client-id: arg
          client-secret: password 
    
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQL82Dialect
      database: POSTGRESQL
      show-sql: false
      hibernate:
         ddl-auto: none 
  datasource:
        type: org.apache.commons.dbcp2.BasicDataSource
        url: jdbc:${database.type}://${database.host}:${database.port}/${database.name}
        name:
        username: ${database.username}
        password: ${database.password}
        dbcp2:
           max-idle: 2
           min-idle: 0
           max-conn-lifetime-millis: 0
           initial-size: 5
           max-total: 10
           test-while-idle: false
           test-on-borrow: false
           log-abandoned: true
           remove-abandoned-on-borrow: true
           remove-abandoned-on-maintenance : true
           remove-abandoned-timeout: 10
           abandoned-usage-tracking: true
           additionalProperties:

  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:config/liquibase/master.xml

  mail:
    host: ${MAIL_HOST:smtp.zoho.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:welcome@iflhousingfinance.com}
    password: ${MAIL_PASSWORD:Welcome@2021}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 60000
          timeout: 60000
          writetimeout: 60000
          
# INFO ENDPOINT CONFIGURATION
info:
 app:
  name: cms
  version: 0.0.1-SNAPSHOT
  description: The doctor service project
  java:
   version: 1.8

management:
 endpoint:
  health:
   show-details: always
 health:
  mail:
    enabled: false

eureka:
  instance:
    preferIpAddress: true
    ip-address: ${ECS_INSTANCE_IP_ADDRESS:127.0.0.1}
    nonSecurePort: ${server.port}
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    homePageUrl: /
  client:
    enabled: true
    healthcheck:
     enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${SERVICE_DISCOVERY_BASE_URL:http://localhost:9001}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

logging:
  level:
    root: ERROR
    com.arg: DEBUG
  file:  /tmp/logs/${spring.application.name}/${spring.application.name}-log.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 
     
     
